export const optimizeResultLabelCopy = {
  savedRunKicker: "저장 진단",
  savedRunFallbackSummary: "현재 답변 축과 URL 상태를 다시 열 수 있게 저장한 진단입니다.",
  runStateDone: "질문 완료",
  runStateDraft: "임시 진단",
  relatedRailCta: "후속 액션 보기",
  relatedRailSummaryLabel: (count: number) => `관련 액션 ${count}개 보기`,
  resultStackKicker: "결과 스택",
  resultStackSection: "진단 요약",
  recommendedStackSection: "권장 스택",
  applyDraftSection: "실행 초안",
  orderRailKicker: "실행 연결",
  sourceUrlLabel: "Source URL",
  openInQuery: "이어서 열기",
  applyDraftLabel: "실행 초안",
  applyDraftActionLabel: "복사",
  applyDraftCopySuccess: "초안을 복사했습니다",
  copyDraftActionLabel: "복사",
  saveDefaultLabel: "현재 진단 저장",
  saveDefaultDescription: "같은 계정으로 /optimize와 보관함에서 다시 열 수 있게 저장했습니다.",
  saveDefaultErrorDescription: "현재 진단을 저장하지 못했습니다.",
  saveDefaultErrorRetryDescription: "현재 진단을 저장하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  saveFailureTitle: "저장에 실패했습니다",
  saveSuccessTitle: "진단을 저장했습니다",
  savePendingLabel: "저장 중...",
} as const;

export const optimizeRailCopy = {
  transferWithInquiry: (kindLabel: string, categoryLabel: string) =>
    `${kindLabel} 진단 결과를 바로 다음 실행으로 넘깁니다. 먼저 ${categoryLabel} 액션 후보를 확인하면, 실제 실행 액션으로 이어집니다.`,
  transferWithExecution: (kindLabel: string, categoryLabel: string) =>
    `${kindLabel} 진단 결과를 바로 ${categoryLabel} 실행 후보로 넘깁니다. 먼저 후보를 확인하면 실행 버튼으로 바로 이어집니다.`,
  emptyBody: (categoryLabel: string) =>
    `아직 ${categoryLabel} 카테고리에 공개된 실행 후보가 충분하지 않습니다. 전체 실행 후보에서 같은 방향 액션을 먼저 찾을 수 있게 연결했습니다.`,
  primaryLabel: (categoryLabel: string) => `${categoryLabel} 실행 보기`,
  title: {
    inquiry: "진단 결과를 다음 실행으로 넘깁니다",
    default: "진단 결과를 다음 실행으로 넘깁니다",
  },
  telemetryEvent: "result_rail_clicked",
} as const;

export const optimizeReadinessCopy = {
  readyLabel: "다음 단계 진행 가능",
  tuningLabel: "주소 보완 필요",
  manualReviewLabel: "수동 확인 권장",
  statusLabel: {
    pass: "준비됨",
    warn: "보정 필요",
    fail: "검토 필요",
    default: "검토 필요",
  },
  identifierFallback: "추가 확인 필요",
} as const;

export const optimizeFlowLabelCopy = {
  stage: {
    stage1: "1. 첫 읽기",
    stage2: "2. 질문 좁히기",
    stage3: "3. 실행 제시",
  },
  stageTitle: {
    stage1: "공개 판독 후 채널 상태를 먼저 고정합니다",
    stage2: "질문으로 병목과 목표를 먼저 정합니다",
    stage3: "결과 스택을 실행 제안으로 연결합니다",
  },
  stageBody: {
    stage1: "공개 표면과 현재 읽기 상태를 먼저 고정합니다",
    stage2: "질문으로 병목과 목표를 먼저 정합니다",
    stage3: "결과 스택을 실행 제안으로 정리합니다",
  },
  workspaceKicker: "대화형 작업면",
  hero: {
    summaryTitle: "이 화면은 채팅형 작업면처럼 바로 반응해야 합니다",
    summaryTitleFallback: "현재 작업면 확인",
    summaryTitleKicker: "대화형 작업면",
  },
  heroBody: "첫 답장에서 채널 종류와 1차 병목을 말하고, 질문 몇 개 안에서 방향을 좁힌 뒤 실행 연결로 넘깁니다.",
  heroSupportedTitle: "지원 채널",
  nextAction: "다음 액션",
  nextActionHint: "다음 실행 대기",
  sidebarContinue: "현재 작업면에서 바로 이어갈 것",
  sidebarHeadline: "지금 바로 이어갈 액션",
  truthItems: {
    headline: "작업 흐름",
    item1: "공개 표면을 먼저 읽습니다",
    item2: "Ask 질문으로 병목을 고정합니다",
    item3: "결과 스택에서 다음 액션을 정합니다",
    item4: "저장 후 이어서 후속 액션으로 넘깁니다",
  },
  truthItemsList: [
    "공개 표면을 먼저 읽습니다",
    "Ask 질문으로 병목을 고정합니다",
    "결과 스택에서 다음 액션을 정합니다",
    "저장 후 이어서 후속 액션으로 넘깁니다",
  ] as const,
  summaryCopy: {
    you: "You",
    next: "Next",
    youLabel: "You",
    nextLabel: "Next",
    promptoryLabel: "Promptory",
    fallback: "공개 표면 기준 병목부터 먼저 고정하고 있습니다.",
  },
  sidebar: {
    heading: "현재 작업면",
    saveSignedIn: "현재 진단 저장",
    saveSignedOut: "로그인 후 저장",
    saveSignedOutHint: "현재 진단을 계정에 보관하려면 로그인이 필요합니다",
    saveResultHint: "같은 계정으로 /optimize와 보관함에서 다시 열 수 있게 저장했습니다.",
    saveFailureToast: "현재 진단을 저장하지 못했습니다.",
    saveSuccessToast: "진단을 저장했습니다",
    saveRetryErrorToast: "현재 진단을 저장하지 못했습니다. 잠시 후 다시 시도해 주세요.",
    saveProgress: "저장 중...",
    saveFailureToastTitle: "저장에 실패했습니다",
    titleCurrent: "현재 상태",
    titleQuestions: "질문 상태",
    titleNext: "다음 실행",
    titleSave: "저장 상태",
    titleChannelType: "채널 분류",
    titleReadiness: "읽기 상태",
    titleNextStep: "다음 단계",
    titleInput: "입력 방식",
    titleNextWork: "다음 작업",
    titleResultConnect: "다음 실행",
  },
  entry: {
    density: "workspace" as const,
    titleKicker: "First Reply Entry",
    title: "URL 던지고 첫 답장 열기",
    body: "URL 확인부터 첫 답장, Ask 질문, 실행 제안까지 한 화면에서 이어집니다.",
    flowLabel: "대화 흐름",
    flowBody: "URL 확인 → Ask 질문 → 실행 제안",
    defaultFlowLabel: "첫 답장",
    defaultFlowBody: "채널 판별 → 첫 병목 → Ask 준비",
    workspaceSubmitLabel: "첫 답장 진행",
    workspaceFlowLabel: "대화 흐름",
    workspaceFlowBody: "URL 확인 → Ask 질문 → 실행 제안",
    submitLabel: "첫 답장 시작",
    defaultSubmitLabel: "첫 답장 받기",
    compactSubmitLabel: "첫 답장 받기",
    afterInputHint: "첫 답장 뒤에 Ask 질문과 실행 추천으로 이어집니다.",
    compactAfterInputHint: "예: YouTube, Naver Blog, Coupang 공개 URL",
    compactFlowLabel: "첫 답장",
    compactFlowBody: "채널 판별 → 첫 병목 → Ask 준비",
    inputPlaceholder: "https://www.youtube.com/@yourchannel",
    steps: [
      "1. URL과 채널 종류를 분류합니다.",
      "2. 첫 병목과 공개 표면 힌트를 읽습니다.",
      "3. Ask 질문으로 방향을 고정합니다.",
    ],
    supportLabel: "지원 채널 예시",
    exampleLabel: "지원 채널 예시",
    connectorBody: "지금은 {supportedChannelHeadline}까지 첫 답장, 질문 준비, 후속 실행이 연결돼 있습니다.",
    defaultResultTitle: "빠른 시작 연결",
    workspaceResultTitle: "현재 작업면 연결",
    defaultResultSubtle: "현재 작업면이 다음 단계로 자연스럽게 이어집니다.",
    compactResultTitle: "빠른 시작 연결",
    compactResultSubtle: "지금은 링크를 넣으면 질문/저장 흐름으로 바로 넘어가게 정리돼 있습니다.",
  },
  surfacePanel: {
    sectionKicker: "Surface Read",
    headlineDefault: "아직 뚜렷한 제목을 읽지 못했습니다.",
    descriptionDefault: "공개 설명 문구가 제한적이라, 다음 단계에서 브라우저 기반 읽기가 더 필요할 수 있습니다.",
    headlineLabel: "Headline",
    actionSignalsLabel: "Action Signals",
    actionSignalsFallback: "지금 바로 보이는 페이지 안에서는 행동으로 이어지는 문장이 아직 많지 않았습니다.",
    notesLabel: "Notes",
    browserFollowupLabel: "Browser Follow-up",
    browserFollowupReasonFallback: "지금 바로 보이는 정보만으로는 실제 첫 화면과 펼침 뒤 문장까지 다 확인하기 어렵습니다.",
  },
  snapshotPanel: {
    sectionKicker: "Read State",
    headline: "지금 이 주소로 어디까지 읽을 수 있는지 먼저 고정합니다",
    hostLabel: "Host",
    confidenceRailLabel: "Confidence Rail",
    nextSurfaceLabel: "Next Surface",
    confidenceSuffix: " 확신도로 읽고 있습니다",
    whatWeKnowLabel: "What We Know",
    whatToReadNextLabel: "What To Read Next",
    normalizedUrlLabel: "Normalized URL",
    readyLabelPrefix: "현재 레디니스",
  },
  diagnosisPreview: {
    readoutTitle: "Diagnosis Readout",
    stateFinal: "확정 readout",
    stateDraft: "임시 readout",
    decisionTraceTitle: "Decision Trace",
    nextReadQueueTitle: "Next Read Queue",
    publicSurfaceTitle: "Public Surface Match",
    headlineLabel: "Headline",
    descriptionLabel: "Description",
    signalLabel: "Action Signal",
  },
  briefBuilder: {
    steps: {
      painLabel: "Pain",
      painQuestion: "지금 가장 아픈 지점은 무엇인가요?",
      goalLabel: "Goal",
      goalQuestion: "이번 최적화의 1순위 목표는 무엇인가요?",
      audienceLabel: "Audience",
      audienceQuestion: "이 채널에 가장 많이 들어오는 사람은 누구인가요?",
      toneLabel: "Tone",
      toneQuestion: "어떤 인상과 말투로 읽혀야 하나요?",
      conversionLabel: "Action",
      conversionQuestion: "최종적으로 사용자가 무엇을 하게 만들고 싶나요?",
      done: "완료",
      current: "현재",
      waiting: "대기",
      emptyStepLabel: "아직 미정",
      currentBadge: "현재 질문",
      continueCta: "이 답변으로 계획 갱신",
      startCta: "질문 시작",
      progressLabel: "Progress",
      recommendedBadge: "추천",
      selectedBadge: "선택",
      openCta: "열기",
      moduleStep1Label: "1. 입력",
      moduleStep2Label: "2. 판독",
      moduleStep3Label: "3. 계획",
      moduleStep4Label: "4. 적용",
      moduleStep1Body: "URL 확인 완료",
      moduleStep2Body: "주소 구조 해석 완료",
      moduleStep3Body: "질문으로 방향 고정",
      moduleStep4Body: "결과 묶음으로 넘김",
      stackStarterLabel: "Starter Stack",
      stackInquiryLabel: "Inquiry Stack",
      stackExecutionLabel: "Execution Stack",
    },
    quickFillCta: "추천값 채우기",
    resetCta: "다시 시작",
    firstProgressFallback: "첫 질문부터 고르면 즉시 방향과 초안이 열립니다.",
    progressSummary: (answered: number, remaining: number) => `${answered}/5개가 고정됐고 남은 질문은 ${remaining}개입니다.`,
    planConsoleLabel: "Plan Console",
    planQuestionTitle: "URL 뒤에서 AI가 먼저 물어야 할 것만 남깁니다",
    planQuestionDescription:
      "문제, 목표, 대상, 톤, 최종 행동을 먼저 고정해야 추천이 묶음처럼 보이지 않고 실행 순서로 보입니다.",
    stackMatchTitle: "Stack Match",
    stackMatchSubtitle: "Stack Match",
    planReadoutTitle: "Plan Readout",
    surfaceReadLabel: "Surface Read",
    benchmarkTitle: "System Benchmark",
    nextOutputTitle: "Next Output",
    constraintTitle: "Constraint Note",
    constraintPlaceholder: "예: 과장 표현 금지, 가격보다 신뢰 강조, 초보자도 이해되는 말투",
    constraintHint: "금지 표현, 우선순위, 브랜드 톤을 적으면 결과 카드에 그대로 반영됩니다.",
    moduleIntroStarter: "채널 타입만 읽은 상태라 시작용 결과 묶음만 먼저 보여 줍니다.",
    moduleIntroDraft: "현재 답변 기준의 임시 추천입니다. 남은 질문을 채우면 더 좁혀집니다.",
    moduleIntroInquiry: "문의 전환에 맞는 플러그인과 결과 묶음을 우선순위대로 정리했습니다.",
    moduleIntroExecution: "채널 운영에 바로 꽂을 수 있는 플러그인과 결과 묶음을 우선순위대로 정리했습니다.",
  },
  presenter: {
    eyebrowCurrent: "현재 상태",
    eyebrowPublic: "공개 판독",
    eyebrowAsk: "질문 계획",
    eyebrowExecution: "실행 추천",
    storyAsk: "질문으로 추천 기준을 고정합니다",
    storyExecution: "결과는 저장과 다음 실행으로 이어집니다",
    storyExecutionBody: "첫 읽기 결과를 저장하고 바로 다음 실행 화면으로 넘깁니다.",
    storyExecutionTitleFallback: "추천 스택에서 바로 다음 액션을 고정합니다",
    heroStates: {
      doneLabel: "공개 표면부터 정직하게 읽습니다",
      doneBody: "채널 종류와 공개 페이지 신호를 먼저 확인합니다.",
      readyBody: "질문을 채우면 결과 스택과 다음 실행이 바로 이어집니다.",
      askPlanTitle: "질문으로 추천 기준을 고정합니다",
      askPlanBody: "누구를 향하고 어떤 행동을 만들지부터 정합니다.",
      executionTitle: "결과는 저장과 다음 실행으로 이어집니다",
      executionBody: "첫 읽기 결과를 저장하고 바로 다음 실행 화면으로 넘깁니다.",
      readyTitle: "공개 표면과 현재 읽기 상태를 먼저 고정합니다",
      readyStateTitle: "URL 확인이 끝났습니다",
      manualReviewTitle: "지원 범위를 먼저 확인해야 합니다",
      tuningTitle: "URL을 조금 더 보정해 주세요",
    },
    invalid: {
      hint: "지원 예시 주소를 눌러 다시 시작하거나, 전체 URL을 그대로 붙여 넣어 주세요.",
      message: "입력한 URL을 다시 확인해 주세요.",
    },
    empty: {
    body: "첫 답장에서 채널 종류와 1차 병목을 말하고, 질문 몇 개 안에서 방향을 좁힌 뒤 실행 제안으로 넘깁니다.",
      title: "이 화면은 채팅형 작업면처럼 바로 반응해야 합니다",
    },
    stateQuestionComplete: "질문 완료",
    stateQuestionInProgress: "질문 진행 중",
    sidebar: {
      titleCurrent: "현재 상태",
      titleQuestions: "질문 상태",
      titleNext: "다음 실행",
      titleSave: "저장 상태",
      titleChannelType: "채널 분류",
      titleReadiness: "읽기 상태",
      titleNextStep: "다음 단계",
      titleInput: "입력 방식",
      titleNextWork: "다음 작업",
    titleResultConnect: "다음 실행",
      heading: "현재 작업면",
    },
    summaryDefault: {
      current: "현재 작업면 확인",
      next: "실행 연결 대기",
    },
    summaryNext: "질문을 좁히고 다음 실행을 정렬하는 단계입니다.",
    summaryAfterSignedIn: "질문을 채우고 저장까지 이어집니다",
    summaryAfterUnsigned: "질문으로 방향을 먼저 고정합니다",
    saveRailBodySignedIn: "URL, 질문 답변, 추천 근거를 함께 저장해 같은 계정에서 같은 작업면으로 바로 돌아오게 합니다.",
    saveRailBodySignedOut: "로그인하면 지금 URL과 답변 상태 그대로 저장해서, 나중에 같은 작업면으로 다시 열 수 있습니다.",
    saveRailSignedInTitle: "현재 진단 결과를 저장합니다",
    saveRailSignedOutTitle: "현재 진단을 계정에 보관하려면 로그인이 필요합니다",
    saveRailEmpty: "아직 저장한 진단이 없습니다. 현재 결과를 저장해 두면 다음에 같은 상태로 바로 다시 열 수 있습니다.",
    emptySaveHint: "아직 저장한 진단이 없습니다. 현재 결과를 저장해 두면 다음에 같은 상태로 바로 다시 열 수 있습니다.",
    truthItems: {
      publicSurface: "공개 표면을 먼저 읽습니다",
      askFix: "Ask 질문으로 병목을 고정합니다",
      setAction: "결과 스택에서 다음 액션을 정합니다",
      forward: "저장 후 이어서 후속 액션으로 이동합니다",
    },
  },
  labels: {
    next: "다음",
    current: "현재",
    aDraft: "A안 복사",
    bDraft: "B안 복사",
    nextActionHint: "다음 실행 대기",
    readyToSave: "계정에 저장 가능",
    lockedSave: "로그인 후 저장 가능",
    resultContinue: "스택 추천과 다음 실행",
  },
  copyDraft: {
    header: "실행 초안",
    copyLinkLabel: "진단 링크 복사",
    copyLinkSuccessTitle: "진단 링크를 복사했습니다",
    copyLinkSuccessDescription: "현재 답변과 URL이 포함된 링크를 바로 공유할 수 있습니다.",
    aDraftLabel: "A안 복사",
    bDraftLabel: "B안 복사",
    aDraftSuccess: "A안을 복사했습니다",
    bDraftSuccess: "B안을 복사했습니다",
    aDraftTitle: "A Draft",
    bDraftTitle: "B Draft",
    titleSuffix: "의 기본 초안을 복사했습니다.",
    placementTitle: "붙일 위치",
    experimentTitle: "Experiment",
    compareTitle: "Compare",
  },
} as const;
