import type {
  ConsoleAuditRecord,
  ConsoleConnectorRecord,
  ConsolePolicyRecord,
} from "@/lib/console/types";

export const consoleConnectors: ConsoleConnectorRecord[] = [
  {
    id: "connector-slack-mcp",
    name: "Slack MCP",
    status: "connected",
    statusTone: "success",
    scope: "messages / search / users / app home",
    mode: "user delegated",
    lastSync: "1분 전",
    note: "request context와 approval surface의 기본 입구입니다.",
  },
  {
    id: "connector-okta",
    name: "Okta",
    status: "write gated",
    statusTone: "brand",
    scope: "grant / expire / group lookup",
    mode: "approval required",
    lastSync: "5분 전",
    note: "권한 변경은 preview + confirm + expiry를 기본값으로 둡니다.",
  },
  {
    id: "connector-jira",
    name: "Jira",
    status: "degraded",
    statusTone: "warning",
    scope: "create / update / link",
    mode: "service account + idempotency key",
    lastSync: "2분 전",
    note: "최근 timeout 비율이 높아 fallback queue와 retry queue를 함께 사용합니다.",
  },
  {
    id: "connector-salesforce",
    name: "Salesforce CRM",
    status: "connected",
    statusTone: "success",
    scope: "opportunity / quote / notes",
    mode: "approval required for write",
    lastSync: "7분 전",
    note: "Deal Desk pack의 system of record입니다.",
  },
  {
    id: "connector-notion",
    name: "Notion / Wiki",
    status: "search only",
    statusTone: "neutral",
    scope: "knowledge retrieval",
    mode: "read only",
    lastSync: "12분 전",
    note: "policy cited answer rate를 올리는 source-of-truth 역할입니다.",
  },
  {
    id: "connector-workday",
    name: "Workday",
    status: "pilot scope",
    statusTone: "brand",
    scope: "travel / people requests",
    mode: "starter pack only",
    lastSync: "25분 전",
    note: "People Ops pack 파일럿 범위에서만 사용 중입니다.",
  },
];

export const consolePolicies: ConsolePolicyRecord[] = [
  {
    id: "policy-employee",
    role: "일반 직원",
    defaultScope: "read / request_create",
    readActions: ["정책 질문", "근거 링크 조회", "요청 상태 확인"],
    writeActions: ["요청 초안 생성", "preview 확인 후 제출"],
    adminActions: [],
    guardrails: ["읽기 작업은 사용자 권한 범위 내 자동", "쓰기 작업은 preview + confirm", "민감 데이터는 source links만 노출"],
  },
  {
    id: "policy-manager",
    role: "매니저 / 승인자",
    defaultScope: "approve / expire / delegate",
    readActions: ["근거 링크 / 영향 범위 확인", "관련 정책과 유사 사례 조회"],
    writeActions: ["승인 / 반려", "만료일 설정", "delegate"],
    adminActions: [],
    guardrails: ["approval card에 risk / impact / source links 포함", "중요 write는 사람이 최종 승인", "사유와 만료일을 audit log에 기록"],
  },
  {
    id: "policy-admin",
    role: "운영 관리자",
    defaultScope: "connector_manage / policy_edit / audit_read",
    readActions: ["failed run 분석", "trace / latency / cost 조회"],
    writeActions: ["connector 설정 수정", "fallback rule 추가", "manual replay"],
    adminActions: ["권한 모델 수정", "audit export", "policy tuning"],
    guardrails: ["write/admin tool 분리", "서비스 계정은 background job 전용", "모든 변경은 trace + audit 분리 기록"],
  },
  {
    id: "policy-security",
    role: "보안 리뷰어",
    defaultScope: "read / secondary approval",
    readActions: ["고위험 요청 감사", "scope / expiry / delegated token 검토"],
    writeActions: ["2인 승인", "보안 메모 남기기"],
    adminActions: ["예외 승인 정책 검토"],
    guardrails: ["ADMIN 액션은 approval required", "짧은 토큰 + 만료 시간 기본", "필요 시 보안팀 참조"],
  },
];

export const consoleAuditTrail: ConsoleAuditRecord[] = [
  {
    id: "audit-240401-001",
    actor: "VP Sales",
    event: "approval_requested",
    target: "ACME Corp 할인 검토",
    at: "2026-04-01 10:47",
    outcome: "대기",
    outcomeTone: "warning",
    detail: "상위 승인 요청 카드 생성, source links 4개 첨부",
  },
  {
    id: "audit-240401-002",
    actor: "Agent Gateway",
    event: "policy_check_passed",
    target: "부산 출장 승인 요청",
    at: "2026-04-01 09:14",
    outcome: "완료",
    outcomeTone: "success",
    detail: "국내 출장 일비 한도, 사전 신청 기한, 전결 범위 자동 확인",
  },
  {
    id: "audit-240401-003",
    actor: "IT Ops manager",
    event: "approval_pending",
    target: "Snowflake 읽기 권한 30일",
    at: "2026-04-01 11:32",
    outcome: "대기",
    outcomeTone: "brand",
    detail: "만료일 2026-05-01, 영향 범위 warehouse read only",
  },
  {
    id: "audit-240401-004",
    actor: "Connector monitor",
    event: "write_failed",
    target: "Salesforce CRM note write",
    at: "2026-04-01 07:52",
    outcome: "실패",
    outcomeTone: "danger",
    detail: "CRM 권한 부족으로 fallback human review queue 등록",
  },
  {
    id: "audit-240401-005",
    actor: "Ops Admin",
    event: "policy_updated",
    target: "Jira MCP timeout fallback",
    at: "2026-04-01 06:55",
    outcome: "완료",
    outcomeTone: "success",
    detail: "retry queue와 manual replay rule을 추가해 degraded run을 완화",
  },
];
