import type { ConsoleRequestRecord } from "@/lib/console/types";

export const consoleRequests: ConsoleRequestRecord[] = [
  {
    id: "req-acme-discount-renewal",
    title: "ACME Corp 할인 검토 / Annual Renewal",
    requester: "김대리",
    pack: "Deal Desk",
    department: "Sales Ops",
    status: "상위 승인 필요",
    statusTone: "warning",
    submittedAt: "2026-04-01 10:42",
    dueAt: "2026-04-01 13:00",
    approver: "VP Sales",
    destination: "Salesforce CRM",
    summary: "Strategic 고객, 요청 할인율 18%, 정책 한도 15% 초과, 마진 영향 -6.2%.",
    sourceLinks: 4,
    risk: "high",
    policyNotes: [
      "Pricing policy 2.1 — 15% 초과 시 상위 승인 필요",
      "Renewal exception guide — Strategic tier는 재협상 근거 필요",
      "CRM closed-won history와 margin guardrail을 함께 확인",
    ],
    evidence: [
      "CRM opportunity snapshot",
      "최근 4건 유사 승인 사례",
      "pricing policy 문서 링크 2개",
      "renewal margin simulation",
    ],
    systemWrites: [
      "승인 결과를 Salesforce opportunity note에 반영",
      "할인 사유와 승인자 정보를 audit log에 기록",
      "필요 시 VP escalation task 생성",
    ],
    timeline: [
      { step: "접수", detail: "Slack thread에서 할인 요청 감지 및 pack 선택", state: "done" },
      { step: "검증", detail: "CRM opportunity / pricing policy / margin simulation 조회", state: "done" },
      { step: "승인", detail: "VP Sales approval card 대기", state: "current" },
      { step: "실행", detail: "승인 후 CRM update + brief DM 예정", state: "upcoming" },
    ],
  },
  {
    id: "req-busan-travel-approval",
    title: "부산 출장 승인 요청 / Tech Conference 2026",
    requester: "박OO",
    pack: "People Ops",
    department: "People Ops",
    status: "승인 대기",
    statusTone: "brand",
    submittedAt: "2026-04-01 09:10",
    dueAt: "2026-04-01 18:00",
    approver: "부서장",
    destination: "Workday + Expense",
    summary: "BEXCO 방문, 550,000 KRW, 정책 범위 내 항목이지만 승인 카드 확인 필요.",
    sourceLinks: 3,
    risk: "medium",
    policyNotes: [
      "국내 출장 일비 한도 내",
      "사전 신청 기한 준수",
      "부서장 전결 가능 범위",
    ],
    evidence: [
      "출장 목적 요약",
      "예상 비용 breakdown",
      "출장 정책 근거 링크 3개",
    ],
    systemWrites: [
      "승인 시 Workday request 생성",
      "Slack 결과 보고와 expense draft 동시 생성",
      "캘린더와 task timeline 업데이트",
    ],
    timeline: [
      { step: "접수", detail: "modal 기반 request intake 저장", state: "done" },
      { step: "검증", detail: "정책, 비용, 사전 신청 기준 자동 확인", state: "done" },
      { step: "승인", detail: "부서장 approval card 확인 대기", state: "current" },
      { step: "실행", detail: "Workday + expense draft 생성 예정", state: "upcoming" },
    ],
  },
  {
    id: "req-snowflake-read-30d",
    title: "Snowflake 읽기 권한 30일 요청",
    requester: "홍길동",
    pack: "IT Access",
    department: "IT Ops",
    status: "승인 대기",
    statusTone: "brand",
    submittedAt: "2026-04-01 11:28",
    dueAt: "2026-04-01 16:00",
    approver: "팀장",
    destination: "Okta + Jira",
    summary: "Analyst 역할, warehouse read only 확장, 30일 만료 접근 + 팀장 승인 권장.",
    sourceLinks: 3,
    risk: "medium",
    policyNotes: [
      "데이터 접근권한 표준 3.2",
      "예외 승인 규정 2.1",
      "만료형 권한은 manager approval + expiry 필수",
    ],
    evidence: [
      "현재 역할과 existing access snapshot",
      "source links ×3",
      "만료일 2026-05-01 preview",
    ],
    systemWrites: [
      "Temporal workflow로 Jira ticket 생성",
      "Okta / IAM 접근권한 부여",
      "재검토 일정과 audit 기록 저장",
    ],
    timeline: [
      { step: "접수", detail: "DM assistant에서 요청 초안 생성", state: "done" },
      { step: "검증", detail: "Slack context + policy + IAM 상태 조회", state: "done" },
      { step: "승인", detail: "팀장 approval modal 대기", state: "current" },
      { step: "실행", detail: "Okta grant + Jira update + canvas summary", state: "upcoming" },
    ],
  },
  {
    id: "req-status-postmortem-brief",
    title: "P1 장애 postmortem pack 생성",
    requester: "최OO",
    pack: "Escalation",
    department: "Support Ops",
    status: "자동 처리 완료",
    statusTone: "success",
    submittedAt: "2026-04-01 08:05",
    dueAt: "2026-04-01 09:00",
    approver: "자동",
    destination: "Jira + Status Page + Confluence",
    summary: "severity 분류, owner 지정, status page update, postmortem draft 생성까지 완료.",
    sourceLinks: 5,
    risk: "low",
    policyNotes: [
      "P1 incident template v3",
      "exec comms policy",
      "public status page change window 확인",
    ],
    evidence: [
      "incident thread summary",
      "Jira incident issue",
      "status page timeline",
      "action items 6개",
    ],
    systemWrites: [
      "status page update 완료",
      "Jira follow-up task 6개 생성",
      "Confluence postmortem draft 생성",
    ],
    timeline: [
      { step: "접수", detail: "channel escalation thread 감지", state: "done" },
      { step: "검증", detail: "severity / owner / impact scope 정리", state: "done" },
      { step: "승인", detail: "low-risk publish rule로 자동 실행", state: "done" },
      { step: "실행", detail: "Status Page + Jira + Confluence 반영 완료", state: "done" },
    ],
  },
  {
    id: "req-cx-refund-vip-exception",
    title: "VIP 환불 예외 검토 / Refund exception",
    requester: "이OO",
    pack: "CX Exception",
    department: "CX Ops",
    status: "실패",
    statusTone: "danger",
    submittedAt: "2026-04-01 07:50",
    dueAt: "2026-04-01 08:30",
    approver: "Finance reviewer",
    destination: "OMS + CRM",
    summary: "주문 데이터는 조회됐지만 CRM 권한 부족으로 recommendation draft가 fallback 상태로 남았습니다.",
    sourceLinks: 2,
    risk: "medium",
    policyNotes: [
      "VIP compensation guide 1.4",
      "refund exception는 finance visibility 필요",
    ],
    evidence: [
      "OMS order summary",
      "CS thread transcript digest",
    ],
    systemWrites: [
      "CRM note write 실패",
      "fallback human review queue 등록",
      "권한 예외 요청 draft 생성",
    ],
    timeline: [
      { step: "접수", detail: "CX thread + order context 수집", state: "done" },
      { step: "검증", detail: "OMS, policy, compensation history 조회", state: "done" },
      { step: "승인", detail: "finance approval 필요", state: "current" },
      { step: "실행", detail: "CRM 권한 부족 해결 후 재시도 예정", state: "upcoming" },
    ],
  },
];

export function getConsoleRequestById(id: string) {
  return consoleRequests.find((request) => request.id === id);
}
